var activityData = [{
    "id": 1,
    "title": "Kraken the Code",
    "subtitle": "Understanding credibility",
    "description": "Learners use the Internet to solve the mystery of The Kraken, a legendary sea creature, while also learning about search terms, keywords, and how to assess the validity and relevance of web sources.",
    "image_url": "https://learning.mozilla.org/img/pages/web-lit-basics/img-kraken-code.jpg",
    "image_retina_url": "https://learning.mozilla.org/img/pages/web-lit-basics/img-kraken-code%402x.jpg",
    "url": "https://mozilla.github.io/mozilla-club-activity-kraken-the-code",
    "difficulty": "Beginner",
    "age_range": "Teens",
    "duration": "15 minutes to 1 hour",
    "twenty_first_century_skills": [ "Problem Solving" ],
    "teaching_kits": [ "Web Literacy Basics" ],
    "authors": [ "Mouse" ],
    "weblit_skills": [ "Search", "Synthesize", "Evaluate" ],
    "locale": "en-US"
  },
  {
    "id": 2,
    "title": "CSS Fonts",
    "subtitle": "Coding/Scripting, Composing, Design",
    "description": "Learners will use webfonts to create moods and tones on webpages, learning about coding, composing, designing, and remixing.",
    "image_url": "https://learning.mozilla.org/img/pages/intermediate-web-lit/letterpress.jpg",
    "url": "https://chadsansing.github.io/curriculum-testing/curriculum-migration/intermediate-web-lit-css-one-migrated/session02-css-fonts.html",
    "difficulty": "Intermediate",
    "age_range": "Teens",
    "duration": "15 minutes to 1 hour",
    "tags": [ "CSS", "Coding" ],
    "twenty_first_century_skills": [ "Problem Solving", "Communication", "Creativity" ],
    "teaching_kits": [ "Intermediate Web Literacy I: Intro to CSS" ],
    "authors": [ "Mozilla" ],
    "weblit_skills": [ "Code", "Compose", "Design", "Evaluate", "Remix", "Revise", "Research", "Search" ],
    "locale": "en-US"
  },
  {
    "id": 3,
    "title": "HTML Puzzle Boxes",
    "subtitle": "Understanding composing for the web",
    "description": "Learners race to sequence the paper boxes labeled with HTML tags, becoming familiar with the most common HTML tags and how to structure a web page.",
    "image_url": "https://learning.mozilla.org/img/pages/web-lit-basics/img-puzzle-boxes.jpg",
    "image_retina_url": "https://learning.mozilla.org/img/pages/web-lit-basics/img-puzzle-boxes%402x.jpg",
    "url": "https://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes",
    "difficulty": "Beginner",
    "age_range": "Kids",
    "duration": "1 to 2 hours",
    "tags": [ "HTML", "Offline" ],
    "twenty_first_century_skills": [ "Creativity" ],
    "teaching_kits": [ "Web Literacy Basics", "Offline Icebreakers" ],
    "authors": [ "Yofie Setiawan, Mozilla Indonesia" ],
    "weblit_skills": [ "Code", "Remix" ],
    "locale": "en-US"
  }, 
  {
    "id": 4,
    "title": "Design a Story for the Web",
    "subtitle": "Understanding Designing",
    "description": "Learners will ideate, sketch and structure a story to create with Webmaker. By brainstorming offline, learners will start thinking about the different ways to create for the Web and get more comfortable with the idea of creating their own content.",
    "image_url": "https://learning.mozilla.org/img/pages/webmaker/designing-webmaker.jpg",
    "url": "http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html",
    "difficulty": "Advanced",
    "age_range": "Adults",
    "duration": "2 to 4 hours",
    "teaching_kits": [ "Read, Write, and Participate with Webmaker" ],
    "authors": [ "Laura", "Bobby" ],
    "weblit_skills": [ "Design", "Remix", "Compose" ],
    "locale": "en-US"
  }, 
  {
    "id": 5,
    "title": "Privacy Coach",
    "subtitle": "Understanding privacy and open practices",
    "description": "Learners mentor their peers to enhance their privacy through their online or digital activities. Knowledge and expertise is shared through discussion or by remixing a response template to report on experiences.",
    "image_url": "https://learning.mozilla.org/img/pages/protect-your-data/img-privacycoach.png",
    "image_retina_url": "https://learning.mozilla.org/img/pages/protect-your-data/img-privacycoach%402x.png 2x",
    "url": "http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session03-privacycoach.html",
    "difficulty": "Beginner",
    "age_range": "Adults",
    "duration": "15 minutes to 1 hour",
    "teaching_kits": [ "Protect Your Data" ],
    "authors": [ "Hive Toronto" ],
    "weblit_skills": [ "Privacy", "Open Practices" ],
    "locale": "en-US"
}]

module.exports = activityData;